#' Write DoCo Count and Final Dictionary to CSV Files
#'
#' This function takes the results from the Blessy function (a list containing the `doco_count` and `final_dict`)
#' and writes them to two separate CSV files.
#'
#' @param results A list containing the `doco_count` matrix and `final_dict` data frame, as generated by the Blessy function.
#' @param doco_count_file The file path where the DoCo count matrix will be saved as a CSV file.
#' @param final_dict_file The file path where the final dictionary will be saved as a CSV file.
#' @examples
#' # Example usage:
#' results <- blessy("path/to/transcript_counts.txt", "path/to/domain_mapping.txt")
#' blessy.write_results_to_csv(results, "doco_count.csv", "final_dict.csv")
#' @export
blessy.output <- function(results, doco_count_file, final_dict_file) {
    # Write the DoCo count matrix to a CSV file
    write.csv(results$doco_count, file = doco_count_file, row.names = FALSE)
    
    # Write the final dictionary data frame to a CSV file
    write.csv(results$final_dict, file = final_dict_file, row.names = FALSE)
}
