#' Write DoCo Count and Final Dictionary to CSV Files
#'
#' This function takes the results from the Blessy function (a list containing the `doco_count` matrix and `final_dict` data frame)
#' and writes them to two separate CSV files in the `/out` folder.
#'
#' @param results A list containing the `doco_count` matrix and `final_dict` data frame, as generated by the Blessy function.
#' @param doco_count_file The file name for the DoCo count matrix CSV (this will be saved in the `/out` folder).
#' @param final_dict_file The file name for the final dictionary CSV (this will be saved in the `/out` folder).
#' @return None. The function writes the `doco_count` and `final_dict` to CSV files in the `/out` directory.
#' @details The function ensures that the `/out` directory exists, and if not, it creates the directory. 
#' The two CSV files, `doco_count` and `final_dict`, are then written to this folder.
#' @examples
#' # Example usage:
#' results <- blessy("path/to/transcript_counts.txt", "path/to/domain_mapping.txt")
#' blessy.output(results, "doco_count.csv", "final_dict.csv")
#' @export
blessy.output <- function(results, doco_count_file, final_dict_file) {
    # Ensure the /out directory exists
    if (!dir.exists("out")) {
        dir.create("out")
    }
    
    # Define the file paths to be in the /out directory
    doco_count_file_path <- file.path("out", doco_count_file)
    final_dict_file_path <- file.path("out", final_dict_file)
    
    # Write the DoCo count matrix to the CSV file in the /out folder
    write.csv(results$doco_count, file = doco_count_file_path, row.names = FALSE)
    
    # Write the final dictionary data frame to the CSV file in the /out folder
    write.csv(results$final_dict, file = final_dict_file_path, row.names = FALSE)
}
